create table if not exists public.profile (
  id bigint primary key check (id = 1), name text not null, surname text default '', title text default '', city text default '',
  bio text default '', about text default '', course text default '', interests jsonb not null default '[]'::jsonb,
  achievements jsonb not null default '[]'::jsonb, telegram text default '', instagram text default '', youtube text default ''
);

create table if not exists public.friends (
  id bigint generated by default as identity primary key, name text not null, relation text default 'Do’st', note text default ''
);

create table if not exists public.acquaintances (
  id bigint generated by default as identity primary key, "firstName" text not null, "lastName" text not null,
  age integer default 0, phone text not null, status text not null default 'pending' check (status in ('pending', 'approved'))
);

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'acquaintances' and column_name = 'firstname') then
    alter table public.acquaintances rename column firstname to "firstName";
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'acquaintances' and column_name = 'lastname') then
    alter table public.acquaintances rename column lastname to "lastName";
  end if;
end $$;

alter table public.profile enable row level security;
alter table public.friends enable row level security;
alter table public.acquaintances enable row level security;

drop policy if exists "Public can read profile" on public.profile;
drop policy if exists "Public can read friends" on public.friends;
drop policy if exists "Public can submit requests" on public.acquaintances;
drop policy if exists "Public can read approved" on public.acquaintances;
drop policy if exists "Authenticated can manage friends" on public.friends;
drop policy if exists "Authenticated can manage acquaintances" on public.acquaintances;

create policy "Public can read profile" on public.profile for select to anon, authenticated using (true);
create policy "Public can read friends" on public.friends for select to anon, authenticated using (true);
create policy "Public can submit requests" on public.acquaintances for insert to anon, authenticated with check (status = 'pending');
create policy "Public can read approved" on public.acquaintances for select to anon, authenticated using (status = 'approved');
create policy "Authenticated can manage friends" on public.friends for all to authenticated using (true) with check (true);
create policy "Authenticated can manage acquaintances" on public.acquaintances for all to authenticated using (true) with check (true);