create table if not exists public.profile (
  id bigint primary key check (id = 1), name text not null, surname text default '', title text default '', city text default '',
  bio text default '', about text default '', course text default '', interests jsonb not null default '[]'::jsonb,
  achievements jsonb not null default '[]'::jsonb, telegram text default '', instagram text default '', youtube text default ''
);

create table if not exists public.friends (
  id bigint generated by default as identity primary key, name text not null, relation text default 'Do’st', note text default ''
);

create table if not exists public.acquaintances (
  id bigint generated by default as identity primary key, "firstName" text not null, "lastName" text not null,
  age integer default 0, phone text not null, status text not null default 'pending' check (status in ('pending', 'approved'))
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null default 'Noma’lum',
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  visited_at timestamptz not null default now()
);

alter table public.reviews add column if not exists name text not null default 'Noma’lum';

insert into public.friends (name, relation, note)
select 'Hojakbar', 'Do’st', 'Mening yaqin do‘stim.'
where not exists (select 1 from public.friends where name = 'Hojakbar');

update public.profile
set instagram = 'https://instagram.com/_sherqulovv_o1',
    youtube = 'https://youtube.com/@Xushnudraxmon01'
where id = 1;

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'acquaintances' and column_name = 'firstname') then
    alter table public.acquaintances rename column firstname to "firstName";
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'acquaintances' and column_name = 'lastname') then
    alter table public.acquaintances rename column lastname to "lastName";
  end if;
end $$;

alter table public.profile enable row level security;
alter table public.friends enable row level security;
alter table public.acquaintances enable row level security;
alter table public.reviews enable row level security;
alter table public.visitor_events enable row level security;

drop policy if exists "Public can read profile" on public.profile;
drop policy if exists "Public can read friends" on public.friends;
drop policy if exists "Authenticated can manage friends" on public.friends;
do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname from pg_policies where schemaname = 'public' and tablename = 'acquaintances'
  loop
    execute format('drop policy if exists %I on public.acquaintances', existing_policy.policyname);
  end loop;
end $$;

create policy "Public can read profile" on public.profile for select to anon, authenticated using (true);
create policy "Public can read friends" on public.friends for select to anon, authenticated using (true);
create policy "Public can submit requests" on public.acquaintances for insert to public with check (status = 'pending');
create policy "Public can read approved" on public.acquaintances for select to anon, authenticated using (status = 'approved');
create policy "Authenticated can manage friends" on public.friends for all to authenticated using (true) with check (true);
create policy "Authenticated can manage acquaintances" on public.acquaintances for all to authenticated using (true) with check (true);
drop policy if exists "Public can submit reviews" on public.reviews;
drop policy if exists "Authenticated can manage reviews" on public.reviews;
drop policy if exists "Anon can submit reviews" on public.reviews;
drop policy if exists "Authenticated can submit reviews" on public.reviews;
create policy "Anon can submit reviews" on public.reviews for insert to anon with check (true);
create policy "Authenticated can submit reviews" on public.reviews for insert to authenticated with check (true);
create policy "Authenticated can manage reviews" on public.reviews for all to authenticated using (true) with check (true);
grant usage on schema public to anon, authenticated;
grant insert on table public.reviews to anon, authenticated;

drop policy if exists "Public can record visitor events" on public.visitor_events;
drop policy if exists "Authenticated can read visitor events" on public.visitor_events;
create policy "Public can record visitor events" on public.visitor_events
  for insert to anon, authenticated
  with check (char_length(visitor_id) between 16 and 100);
create policy "Authenticated can read visitor events" on public.visitor_events
  for select to authenticated using (true);
grant insert on table public.visitor_events to anon, authenticated;
grant select on table public.visitor_events to authenticated;

create or replace function public.get_monthly_visitor_stats()
returns table(month date, unique_visitors bigint, visits bigint)
language sql
security definer
set search_path = public
as $$
  select
    date_trunc('month', visited_at)::date as month,
    count(distinct visitor_id) as unique_visitors,
    count(*) as visits
  from public.visitor_events
  where visited_at >= date_trunc('month', current_date) - interval '11 months'
  group by 1
  order by 1;
$$;

revoke all on function public.get_monthly_visitor_stats() from public;
grant execute on function public.get_monthly_visitor_stats() to authenticated;